# Generated by Django 5.2 on 2025-12-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.CharField(blank='00000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
